players:
  aimaina: Aimaina
  brandnew_: BranDNeW_
  chip_idiot: Chip Idiot
  ssf_deadanddoom: DeadandDoom
  drdexxerrace: Dexxer
  exilezoomz: Exilezoomz
  fitegarr: Fitegarr
  furyotic: Furyotic
  goratha2: Goratha
  gucciracing: GucciPradas
  sanguinespirit: Havoc
  ssf_heshlathird: Heshla
  karvarousku1: Karvarousku
  keldorn_race: Keldorn
  meshamaan_racer: MeShaMaaN
  mattzourys: Mattzour
  nicparry: NicParry
  ovvy: Ovvy
  paak_fb: Paak_HC
  pookieeh: Pookieeh
  pruonna2: Pruonna2
  celostrophus: Quantrik
  queaw: Queaw
  r0pk3: r0pk3
  so0lep: so0le
  steelbanker: Steelmage
  storm159: storm159
  terence_race: Terence_
  yeauwh: Tippop
  tytykiller_race: TyTyKiller
  ventruaxd: Ventrua
  xaitv_race: XaiTV
  zepyh: Zepyh
  ssf_zizaran: Zizaran
